---
title: "ProyectoTD2022"
author: "Grupo K"
date: '2022-04-19'
output:
# Salida html, 
  html_document:
    echo: yes
    number_sections: no
    theme: lumen
    toc: yes
# Salida pdf
  pdf_document:
    toc: yes      # Tabla de contenido (índice)
    toc_depth: 3  # Número de niveles de la tabla de contenido (índice) # 1, ##2,###3
    number_sections: no # Numeración de las secciones

---
### Instalación de paquetes necesarios:
```{r,echo=T, message = F, error = F, warning = F}

# Especificamos las librerías necesarias en esta lista

packages = c("tidyverse","knitr","ggplot2")

#use this function to check if each package is on the local machine
#if a package is installed, it will be loaded
#if any are not, the missing package(s) will be installed and loaded
package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE,repos='http://cran.rediris.es')
  }
  library(x, character.only = TRUE)
})

#verify they are loaded
search()

```

### Numeración de los data frames correspondientes a las estaciones de medida:

1. Datos diarios del sensor de ruido ubicado en el barrio de Ruzafa, en la calle Sueca Esq. Denia
2. Datos diarios del sensor de ruido ubicado en el barrio de Ruzafa, en la calle Cádiz, 16
3. Datos diarios del sensor de ruido ubicado en el barrio de Ruzafa, en la calle Cádiz, 3
4. Datos diarios del sensor de ruido ubicado en el barrio de Ruzafa, en la calle Cuba, 3
5. Datos diarios del sensor de ruido ubicado en el barrio de Ruzafa, en la calle Sueca, 2
6. Datos diarios del sensor de ruido ubicado en el barrio de Ruzafa, en la calle Sueca, 61
7. Datos diarios del sensor de ruido ubicado en el barrio de Ruzafa, en la calle Sueca, 32
8. Datos diarios del sensor de ruido ubicado en el barrio de Ruzafa, en la calle Carles Cervera, Chaflán Reina Doña María
9. Datos diarios del sensor de ruido ubicado en el barrio de Ruzafa, en la calle Salvador Abril Chaflán Maestro José Serrano
10. Datos diarios del sensor de ruido ubicado en el barrio de Ruzafa, en la calle Vivons Chaflán Cádiz
11. Datos diarios del sensor de ruido ubicado en el barrio de Ruzafa, en la calle Carles Cervera, 34
12. Datos diarios del sensor de ruido ubicado en el barrio de Ruzafa, en la calle Puerto Rico, 21
13. Datos diarios del sensor de ruido ubicado en el barrio de Ruzafa, en la calle Doctor Serrano, 21
14. Datos diarios del sensor de ruido ubicado en el barrio de Ruzafa, en la calle General Prim Chaflán Donoso Cortés